#!/bin/bash

echo "==================================="
echo "Database Schema Baseline Export"
echo "==================================="
echo ""
echo "This script will export your current database schema as a baseline."
echo ""
echo "Option 1: If you have the database password:"
echo "  supabase db dump --schema public -f supabase/migrations/20250831100000_baseline.sql --password YOUR_PASSWORD"
echo ""
echo "Option 2: If you have linked the project:"
echo "  supabase link --project-ref dmyhbzzrpjfbevehpwkp"
echo "  supabase db dump --schema public -f supabase/migrations/20250831100000_baseline.sql"
echo ""
echo "Option 3: Manual export from Supabase Dashboard:"
echo "  1. Go to https://supabase.com/dashboard/project/dmyhbzzrpjfbevehpwkp/sql"
echo "  2. Run this query to get your schema:"
echo ""
echo "     -- Get all table definitions"
echo "     SELECT"
echo "       'CREATE TABLE ' || table_name || ' (' || E'\\n' ||"
echo "       string_agg("
echo "         '  ' || column_name || ' ' || data_type ||"
echo "         CASE"
echo "           WHEN character_maximum_length IS NOT NULL"
echo "           THEN '(' || character_maximum_length || ')'"
echo "           ELSE ''"
echo "         END ||"
echo "         CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END ||"
echo "         CASE WHEN column_default IS NOT NULL THEN ' DEFAULT ' || column_default ELSE '' END,"
echo "         E',\\n'"
echo "       ) || E'\\n);'"
echo "     FROM information_schema.columns"
echo "     WHERE table_schema = 'public'"
echo "     GROUP BY table_name;"
echo ""
echo "  3. Save the output to supabase/migrations/20250831100000_baseline.sql"
echo ""
echo "==================================="