/**
 * Retrieve the short-lived App Store Connect JWT used for calling Apple APIs.
 *
 * The JWT itself is generated by the dedicated `apple-jwt` Edge Function which
 * handles signing with the private key stored in Supabase Vault. This helper:
 * - authenticates with that function using the `service_role` key (never expose
 *   this to the browser) so the signing key remains server-side;
 * - surfaces structured errors so callers can return actionable messages; and
 * - keeps timing data handy for observability when request IDs are supplied.
 *
 * The optional `requestId` lets upstream callers correlate logs across multiple
 * boundary hops (eg. data-initialisation jobs or history fetch pipelines).
 */
export async function getAppleJWT(requestId?: string): Promise<string> {
  const supabaseUrl = Deno.env.get('SUPABASE_URL')
  const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')

  if (!supabaseUrl || !supabaseServiceKey) {
    throw new Error('Supabase URL or service role key is not configured')
  }

  const startTime = Date.now()

  try {
    const response = await fetch(`${supabaseUrl}/functions/v1/apple-jwt`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${supabaseServiceKey}`,
        'Content-Type': 'application/json'
      }
    })

    if (!response.ok) {
      let errorMessage = 'Failed to generate Apple JWT'

      try {
        const errorData = await response.json()
        if (errorData?.error) {
          errorMessage = errorData.error
        }
        console.error(
          requestId ? `[${requestId}] ❌ Apple JWT generation failed:` : '❌ Apple JWT generation failed:',
          errorData
        )
      } catch (_jsonParseError) {
        const fallback = await response.text()
        console.error(
          requestId ? `[${requestId}] ❌ Apple JWT generation failed (non-JSON body)` : '❌ Apple JWT generation failed (non-JSON body)',
          fallback
        )
        if (fallback) {
          errorMessage = `${errorMessage}: ${fallback}`
        }
      }

      throw new Error(errorMessage)
    }

    const data = await response.json()
    return data.jwt
  } catch (error) {
    const duration = Date.now() - startTime
    console.error(
      requestId ? `[${requestId}] ERROR fetching Apple JWT after ${duration}ms:` : `ERROR fetching Apple JWT after ${duration}ms:`,
      error
    )
    throw new Error(error instanceof Error ? error.message : 'Failed to get Apple JWT')
  }
}
